# Generated by Django 3.1.5 on 2021-01-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210112_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='img_1',
        ),
    ]
